name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run flake8 for linting
      - name: Run flake8
        run: |
          flake8 . --max-line-length 127

      # Step 5: Run black to check code formatting
      - name: Run black (check)
        run: |
          black --check .

      # Step 6: Run pytest for unit tests
      - name: Run tests
        run: |
          pytest
